### ISSUE TITLE
a small mistake

### ISSUE THREAD

**Issue by Vera-He** [JiangAo621/JiangA#2]
There is something wrong with the method you use to calculate 'numB'. You use '||' to connect  (num1 == guess2) , (num1 == guess3) and then add them together, but you may mistaken the precedence of '||' and '+'. So the procedure won't go as what you think.
Give an example: if the answer is '5 2 0', and user's guess is '0 2 5', it is supposed to get the information '1A2B', but the program gives the wrong '1A1B'.

**Comment by yuralty** [comment]
Has this bug been fixed?

**Comment by JiangAo621** [comment]
Yes,I have already fixed the bug.
